Add launching diagnostics aggregator, and yaml configuration
fetchrobotics/fetch_robots pull request #6
Opened 2016-02-26 22:53 UTC by erelson

Needed for https://github.com/fetchrobotics/engineering/issues/532

2016-02-26 22:57 UTC, erelson commented
!review

2016-02-26 22:58 UTC, erelson commented
Will squash once any grouping/naming tweaks have been done.

2016-08-02 18:01 UTC, erelson commented
I have re-based and squashed this.  Any reason we don't want to get this merged? (possibly we don't want this on freights for now)

2017-03-14 11:27 UTC, ensonic commented on freight_bringup/config/analyzers.yaml
> +analyzers:
Please also aggregate the battery status (power), see
https://github.com/Arkapravo/turtlebot/blob/master/turtlebot_bringup/config/diagnostics.yaml#L19

2017-03-22 12:51 UTC, ensonic commented
Is there any chance that this will ever get merged, or do we need to manually integrate this?

2017-06-12 01:53 UTC, mikeferguson requested changes

2017-06-12 01:53 UTC, mikeferguson commented on fetch_bringup/launch/include/aggregator.launch.xml
> +        name="diag_agg" args="CPP" output="screen" >
while it is longer, I would suggest making the name "diagnostic_aggregator" to match other robots (like turtlebot)

2017-06-12 01:53 UTC, mikeferguson commented on freight_bringup/launch/include/aggregator.launch.xml
> +        name="diag_agg" args="CPP" output="screen" >
while it is longer, I would suggest making the name "diagnostic_aggregator" to match other robots (like turtlebot)

2017-06-12 01:53 UTC, mikeferguson commented on freight_bringup/launch/include/aggregator.launch.xml
> +        pkg="diagnostic_aggregator" type="aggregator_node"
need to add a runtime dependency on diagnostic_aggregator for both fetch/freight_bringup packages, else this will break the world

2017-06-12 01:53 UTC, mikeferguson commented on freight_bringup/config/analyzers.yaml
> +analyzers:
It appears we don't actually publish anything about battery to diagnostics at this time, so we can't aggregate it.

2017-06-12 01:54 UTC, mikeferguson commented
@erelson -- big issue is missing depend -- if you fix this, we'll merge. I would suggest we also change the name of the nodes though for consistency with other platforms (and diag_agg isn't super specific unless you know what it already means)

2017-06-12 16:52 UTC, erelson commented on freight_bringup/launch/include/aggregator.launch.xml
> +        pkg="diagnostic_aggregator" type="aggregator_node"
Added :+1:

2017-06-12 16:53 UTC, erelson commented
@mikeferguson I've added the changes suggested

2017-06-12 17:16 UTC, mikeferguson commented on fetch_bringup/launch/include/aggregator.launch.xml
> +        name="diagnostic_aggregator" args="CPP" output="screen" >
what is the args CPP for? (I hadn't noticed that before)

2017-06-12 17:20 UTC, erelson commented on fetch_bringup/launch/include/aggregator.launch.xml
> +        name="diagnostic_aggregator" args="CPP" output="screen" >
I wondered this as well when making the change but didn't look it up...

2017-06-12 17:33 UTC, mikeferguson approved these changes

2017-06-12 17:34 UTC, merged